/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter/index.vue')['default']
    AppNav: typeof import('./components/AppNav/index.vue')['default']
    DevelopmentProgress: typeof import('./components/DevelopmentProgress/index.vue')['default']
    ImageSelector: typeof import('./components/ImageSelector/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sphere: typeof import('./components/Sphere/index.vue')['default']
  }
}
